Repository JeanPhilippeKernel/RendererEngine, pull requests merged in 2021-11, with the labels that each got.

#115 refactored shaders management
  ZEngine/include/ZEngine/Rendering/Shaders/Compilers/CompilationStage.h
  ZEngine/include/ZEngine/Rendering/Shaders/Compilers/ICompilerStage.h
  ZEngine/include/ZEngine/Rendering/Shaders/Compilers/LinkageStage.h
  ZEngine/include/ZEngine/Rendering/Shaders/Compilers/ShaderCompiler.h
  ZEngine/include/ZEngine/Rendering/Shaders/Compilers/ValidationStage.h
  ZEngine/include/ZEngine/Rendering/Shaders/Shader.h
  ZEngine/include/ZEngine/Rendering/Shaders/ShaderEnums.h
  ZEngine/include/ZEngine/Rendering/Shaders/ShaderInformation.h
  ZEngine/include/ZEngine/Rendering/Shaders/ShaderReader.h
  ZEngine/src/CMakeLists.txt
  ZEngine/src/CompilationStage.cpp
  ZEngine/src/ICompilerStage.cpp
  ZEngine/src/LinkageStage.cpp
  ZEngine/src/Shader.cpp
  ZEngine/src/ShaderCompiler.cpp
  ZEngine/src/ShaderReader.cpp
  ZEngine/src/ValidationStage.cpp
Labels: enhancement, area-rendering

#117 updated readme
  README.md
Labels: enhancement

#119 fixed shader multiple compilation
  ZEngine/include/ZEngine/Managers/IAssetManager.h
  ZEngine/include/ZEngine/Managers/IManager.h
  ZEngine/include/ZEngine/Managers/ShaderManager.h
  ZEngine/include/ZEngine/Managers/TextureManager.h
  ZEngine/src/ShaderManager.cpp
  ZEngine/src/TextureManager.cpp
Labels: enhancement, area-rendering

#122 moved layer stack to smart ptr
  Examples/Sandbox/src/Sandbox.cpp
  Examples/Sandbox3D/src/Sandbox.cpp
  ZEngine/include/ZEngine/Layers/LayerStack.h
  ZEngine/include/ZEngine/Window/CoreWindow.h
  ZEngine/src/CoreWindow.cpp
  ZEngine/src/GraphicRenderer.cpp
  ZEngine/src/GraphicScene.cpp
  ZEngine/src/LayerStack.cpp
  ZEngine/src/OpenGLWindow.cpp
Labels: enhancement

#126 support of docking
  Examples/Sandbox/src/Components/AboutUIComponent.h
  Examples/Sandbox/src/Components/DemoUIComponent.h
  Examples/Sandbox3D/src/Components/AboutUIComponent.h
  Examples/Sandbox3D/src/Components/DemoUIComponent.h
  Tetragrama/src/CMakeLists.txt
  Tetragrama/src/Components/AboutUIComponent.h
  Tetragrama/src/Components/DemoUIComponent.h
  Tetragrama/src/Components/DockspaceUIComponent.cpp
  Tetragrama/src/Components/DockspaceUIComponent.h
  Tetragrama/src/Editor.cpp
  Tetragrama/src/Editor.h
  Tetragrama/src/EntryPoint.cpp
  ZEngine/include/ZEngine/Components/UIComponent.h
  ZEngine/include/ZEngine/Components/UIComponentEvent.h
  ZEngine/include/ZEngine/Event/CoreEvent.h
  ZEngine/include/ZEngine/Event/EventCategory.h
  ZEngine/include/ZEngine/Event/EventType.h
  ZEngine/include/ZEngine/Layers/ImguiLayer.h
  ZEngine/include/ZEngine/Window/SDLWin/OpenGLWindow.h
  ZEngine/include/ZEngine/ZEngine.h
  ZEngine/src/ImguiLayer.cpp
  ZEngine/src/UIComponent.cpp
Labels: area-linux, area-window, area-ui

#118 Add Contributing doc
  Code-of-Conduct.md
  Contributing.md
Labels: documentation

#136 added scene viewport ui
  Tetragrama/src/Components/DockspaceUIComponent.cpp
  Tetragrama/src/Components/SceneViewportUIComponent.cpp
  Tetragrama/src/Components/SceneViewportUIComponent.h
  Tetragrama/src/Editor.cpp
  ZEngine/include/ZEngine/Components/UIComponent.h
  ZEngine/src/GlfwWindow/OpenGLWindow.cpp
  ZEngine/src/UIComponent.cpp
Labels: area-ui

#137 Introduced Framebuffer
  Scripts/BuildEngine.ps1
  Tetragrama/src/Components/SceneViewportUIComponent.cpp
  Tetragrama/src/Editor.cpp
  Tetragrama/src/Layers/ExampleLayer.cpp
  Tetragrama/src/Layers/ExampleLayer.h
  Tetragrama/src/Layers/UserInterfaceLayer.h
  Tetragrama/src/pch.h
  ZEngine/include/ZEngine/Layers/Layer.h
  ZEngine/include/ZEngine/Rendering/Buffers/FrameBuffers/FrameBufferSpecification.h
  ZEngine/include/ZEngine/Rendering/Buffers/FrameBuffers/Framebuffer.h
  ZEngine/include/ZEngine/Rendering/Renderers/GraphicRenderer.h
  ZEngine/include/ZEngine/Rendering/Scenes/GraphicScene.h
  ZEngine/src/FrameBuffer.cpp
  ZEngine/src/GlfwWindow/OpenGLWindow.cpp
  ZEngine/src/GraphicRenderer.cpp
  ZEngine/src/GraphicRenderer3D.cpp
  ZEngine/src/GraphicScene.cpp
  ZEngine/src/GraphicScene2D.cpp
  ZEngine/src/GraphicScene3D.cpp
  ZEngine/src/UIComponent.cpp
Labels: area-rendering, area-window, area-ui

#125 #113 Add precompiled header support (pch.h)
  ZEngine/include/ZEngine/pch.h
  ZEngine/src/CMakeLists.txt
  ZEngine/src/CompilationStage.cpp
  ZEngine/src/CoreWindow.cpp
  ZEngine/src/CubeGeometry.cpp
  ZEngine/src/Engine.cpp
  ZEngine/src/FirstPersonShooterCamera.cpp
  ZEngine/src/FirstPersonShooterCameraController.cpp
  ZEngine/src/GraphicRenderer.cpp
  ZEngine/src/GraphicRenderer2D.cpp
  ZEngine/src/GraphicRenderer3D.cpp
  ZEngine/src/GraphicRendererStorage.cpp
  ZEngine/src/GraphicScene.cpp
  ZEngine/src/GraphicScene2D.cpp
  ZEngine/src/GraphicScene3D.cpp
  ZEngine/src/GraphicVertex.cpp
  ZEngine/src/ICompilerStage.cpp
  ZEngine/src/IDevice.cpp
  ZEngine/src/ImguiLayer.cpp
  ZEngine/src/LayerStack.cpp
  ZEngine/src/LinkageStage.cpp
  ZEngine/src/Logger.cpp
  ZEngine/src/Math.cpp
  ZEngine/src/Mesh.cpp
  ZEngine/src/MeshBuilder.cpp
  ZEngine/src/MixedTextureMaterial.cpp
  ZEngine/src/OrbitCamera.cpp
  ZEngine/src/OrbitCameraController.cpp
  ZEngine/src/OrthographicCamera.cpp
  ZEngine/src/OrthographicCameraController.cpp
  ZEngine/src/PerspectiveCamera.cpp
  ZEngine/src/PerspectiveCameraController.cpp
  ZEngine/src/QuadGeometry.cpp
  ZEngine/src/SDL2Window/OpenGLContext.cpp
  ZEngine/src/SDL2Window/OpenGLWindow.cpp
  ZEngine/src/Shader.cpp
  ZEngine/src/ShaderCompiler.cpp
  ZEngine/src/ShaderManager.cpp
  ZEngine/src/ShaderMaterial.cpp
  ZEngine/src/ShaderReader.cpp
  ZEngine/src/SquareGeometry.cpp
  ZEngine/src/StandardMaterial.cpp
  ZEngine/src/Texture2D.cpp
  ZEngine/src/TextureManager.cpp
  ZEngine/src/UIComponent.cpp
  ZEngine/src/ValidationStage.cpp
  ZEngine/src/pch.cpp
Labels: enhancement

#140 implemented viewport resizing event
  Tetragrama/src/Components/DockspaceUIComponent.cpp
  Tetragrama/src/Components/Events/SceneTextureAvailableEvent.h
  Tetragrama/src/Components/Events/SceneViewportResizedEvent.h
  Tetragrama/src/Components/SceneViewportUIComponent.cpp
  Tetragrama/src/Components/SceneViewportUIComponent.h
  Tetragrama/src/Editor.cpp
  Tetragrama/src/Editor.h
  Tetragrama/src/EntryPoint.cpp
  Tetragrama/src/Layers/ExampleLayer.cpp
  Tetragrama/src/Layers/ExampleLayer.h
  Tetragrama/src/Layers/UserInterfaceLayer.cpp
  Tetragrama/src/Layers/UserInterfaceLayer.h
  ZEngine/include/ZEngine/Components/UIComponentEvent.h
  ZEngine/include/ZEngine/Controllers/ICameraController.h
  ZEngine/include/ZEngine/Controllers/OrthographicCameraController.h
  ZEngine/include/ZEngine/Controllers/PerspectiveCameraController.h
  ZEngine/include/ZEngine/Event/EventDispatcher.h
  ZEngine/include/ZEngine/Event/EventType.h
  ZEngine/include/ZEngine/Rendering/Buffers/FrameBuffers/Framebuffer.h
  ZEngine/include/ZEngine/Rendering/Cameras/Camera.h
  ZEngine/include/ZEngine/Rendering/Scenes/GraphicScene.h
  ZEngine/include/ZEngine/ZEngine.h
  ZEngine/src/FrameBuffer.cpp
  ZEngine/src/GraphicScene.cpp
  ZEngine/src/OrthographicCameraController.cpp
  ZEngine/src/PerspectiveCameraController.cpp
  ZEngine/src/SDL2Window/OpenGLWindow.cpp
Labels: area-linux, area-window, area-ui

#141 added macos build & renamed example layer
  .github/workflows/macOS-build.yml
  Tetragrama/src/Editor.cpp
  Tetragrama/src/Layers/RenderingLayer.cpp
  Tetragrama/src/Layers/RenderingLayer.h
Labels: DevOps, area-macOS

#142 fixed viewport input management
  Examples/Sandbox/src/Components/AboutUIComponent.h
  Examples/Sandbox/src/Components/DemoUIComponent.h
  Examples/Sandbox3D/src/Components/AboutUIComponent.h
  Examples/Sandbox3D/src/Components/DemoUIComponent.h
  Tetragrama/src/Components/AboutUIComponent.h
  Tetragrama/src/Components/DemoUIComponent.h
  Tetragrama/src/Components/DockspaceUIComponent.cpp
  Tetragrama/src/Components/DockspaceUIComponent.h
  Tetragrama/src/Components/Events/SceneViewportFocusedEvent.h
  Tetragrama/src/Components/Events/SceneViewportUnfocusedEvent.h
  Tetragrama/src/Components/SceneViewportUIComponent.cpp
  Tetragrama/src/Components/SceneViewportUIComponent.h
  Tetragrama/src/Editor.cpp
  Tetragrama/src/Layers/RenderingLayer.cpp
  Tetragrama/src/Layers/RenderingLayer.h
  Tetragrama/src/Layers/UserInterfaceLayer.h
  ZEngine/include/ZEngine/Components/UIComponent.h
  ZEngine/include/ZEngine/Event/EventType.h
  ZEngine/src/ImguiLayer.cpp
Labels: Feature request, area-linux, area-window, area-ui, area-macOS

#156 split scene implementation for 2d and 3d
  ZEngine/include/ZEngine/Rendering/Renderers/GraphicRenderer.h
  ZEngine/include/ZEngine/Rendering/Renderers/GraphicRenderer2D.h
  ZEngine/include/ZEngine/Rendering/Renderers/GraphicRenderer3D.h
  ZEngine/include/ZEngine/Rendering/Renderers/Storages/GraphicRendererStorage.h
  ZEngine/include/ZEngine/pch.h
  ZEngine/src/GraphicRenderer.cpp
  ZEngine/src/GraphicRenderer2D.cpp
  ZEngine/src/GraphicRenderer3D.cpp
  ZEngine/src/GraphicScene2D.cpp
  ZEngine/src/GraphicScene3D.cpp
Labels: enhancement

#157 removed sandbox 3d project
  CMakeLists.txt
  Examples/Sandbox3D/CMakeLists.txt
  Examples/Sandbox3D/src/CMakeLists.txt
  Examples/Sandbox3D/src/Components/AboutUIComponent.h
  Examples/Sandbox3D/src/Components/DemoUIComponent.h
  Examples/Sandbox3D/src/Layers/ExampleLayer.cpp
  Examples/Sandbox3D/src/Layers/ExampleLayer.h
  Examples/Sandbox3D/src/Layers/GUILayer.h
  Examples/Sandbox3D/src/Sandbox.cpp
  README.md
Labels: enhancement
