Repository JeanPhilippeKernel/RendererEngine, pull requests merged in 2022-09, with the labels that each got.

#203 Improving Lighting support
  Resources/Editor/Scenes/SampleScene.zengine
  Resources/Windows/Shaders/standard_shader.glsl
  Tetragrama/src/Components/InspectorViewUIComponent.cpp
  ZEngine/include/ZEngine/Rendering/Buffers/UniformBuffer.h
  ZEngine/include/ZEngine/Rendering/Components/LightComponent.h
  ZEngine/include/ZEngine/Rendering/Lights/DirectionalLight.h
  ZEngine/include/ZEngine/Rendering/Lights/Light.h
  ZEngine/include/ZEngine/Rendering/Lights/LightEnums.h
  ZEngine/include/ZEngine/Rendering/Materials/StandardMaterial.h
  ZEngine/include/ZEngine/Rendering/Renderers/GraphicRenderer.h
  ZEngine/include/ZEngine/Rendering/Renderers/GraphicRenderer2D.h
  ZEngine/include/ZEngine/Rendering/Renderers/GraphicRenderer3D.h
  ZEngine/include/ZEngine/Rendering/Renderers/Pipelines/GraphicRendererDrawStage.h
  ZEngine/include/ZEngine/Rendering/Renderers/Storages/GraphicRendererStorage.h
  ZEngine/include/ZEngine/ZEngine.h
  ZEngine/src/DirectionalLight.cpp
  ZEngine/src/GraphicRenderer.cpp
  ZEngine/src/GraphicRenderer2D.cpp
  ZEngine/src/GraphicRenderer3D.cpp
  ZEngine/src/GraphicRendererDrawStage.cpp
  ZEngine/src/GraphicScene.cpp
  ZEngine/src/GraphicScene3DSerializer.cpp
  ZEngine/src/Light.cpp
  ZEngine/src/StandardMaterial.cpp
Labels: enhancement, Feature request

#207 fixed linux pipeline
  .github/workflows/linux-build.yml
Labels: bug, area-linux

#206 fixed math lib exposition
  Tetragrama/src/CMakeLists.txt
  Tetragrama/src/EntryPoint.cpp
  ZEngine/include/ZEngine/Maths/Math.h
  ZEngine/src/Math.cpp
Labels: enhancement

#204 abstracted frameBuffer attachment
  .clang-format
  Resources/Windows/Shaders/standard_shader.glsl
  Tetragrama/src/Components/LogUIComponent.cpp
  Tetragrama/src/Components/SceneViewportUIComponent.cpp
  Tetragrama/src/Components/SceneViewportUIComponent.h
  Tetragrama/src/Editor.cpp
  Tetragrama/src/Layers/RenderLayer.cpp
  Tetragrama/src/Layers/RenderLayer.h
  Tetragrama/src/Layers/UILayer.cpp
  Tetragrama/src/MessageToken.h
  Tetragrama/src/pch.h
  ZEngine/include/ZEngine/Core/IGraphicObject.h
  ZEngine/include/ZEngine/Helpers/FrameBufferTextureHelpers.h
  ZEngine/include/ZEngine/Logging/Logger.h
  ZEngine/include/ZEngine/Logging/LoggerConfiguration.h
  ZEngine/include/ZEngine/Rendering/Buffers/FrameBuffers/FrameBufferAttachmentSpecification.h
  ZEngine/include/ZEngine/Rendering/Buffers/FrameBuffers/FrameBufferSpecification.h
  ZEngine/include/ZEngine/Rendering/Buffers/FrameBuffers/FrameBufferTextureFormatEnums.h
  ZEngine/include/ZEngine/Rendering/Buffers/FrameBuffers/FrameBufferTextureSpecification.h
  ZEngine/include/ZEngine/Rendering/Buffers/FrameBuffers/Framebuffer.h
  ZEngine/include/ZEngine/Rendering/Buffers/PixelBuffer.h
  ZEngine/include/ZEngine/Rendering/Scenes/GraphicScene.h
  ZEngine/src/FrameBuffer.cpp
  ZEngine/src/FrameBufferTextureHelpers.cpp
  ZEngine/src/GraphicRenderer3D.cpp
  ZEngine/src/GraphicRendererStartFrameBindingStage.cpp
  ZEngine/src/GraphicScene.cpp
  ZEngine/src/Logger.cpp
Labels: Feature request, area-rendering, area-linux, area-window, area-ui, area-macOS

#209 remove libudev from linux pipeline
  .github/workflows/linux-build.yml
Labels: DevOps
