Repository JeanPhilippeKernel/RendererEngine, pull requests merged in 2022-08, with the labels that each got.

#182 Introduced Entity Component System support
  Tetragrama/src/Components/HierarchyViewUIComponent.cpp
  Tetragrama/src/Components/HierarchyViewUIComponent.h
  Tetragrama/src/Components/InspectorViewUIComponent.cpp
  Tetragrama/src/Components/InspectorViewUIComponent.h
  Tetragrama/src/Components/ProjectViewUIComponent.cpp
  Tetragrama/src/Components/ProjectViewUIComponent.h
  Tetragrama/src/Layers/RenderingLayer.cpp
  Tetragrama/src/Layers/RenderingLayer.h
  Tetragrama/src/Layers/UserInterfaceLayer.cpp
  Tetragrama/src/Layers/UserInterfaceLayer.h
  ZEngine/include/ZEngine/Inputs/IDevice.h
  ZEngine/include/ZEngine/Rendering/Components/CameraComponent.h
  ZEngine/include/ZEngine/Rendering/Components/GeometryComponent.h
  ZEngine/include/ZEngine/Rendering/Components/LightComponent.h
  ZEngine/include/ZEngine/Rendering/Components/MaterialComponent.h
  ZEngine/include/ZEngine/Rendering/Components/NameComponent.h
  ZEngine/include/ZEngine/Rendering/Components/TransformComponent.h
  ZEngine/include/ZEngine/Rendering/Entities/GraphicSceneEntity.h
  ZEngine/include/ZEngine/Rendering/Geometries/CubeGeometry.h
  ZEngine/include/ZEngine/Rendering/Lights/Light.h
  ZEngine/include/ZEngine/Rendering/Materials/StandardMaterial.h
  ZEngine/include/ZEngine/Rendering/Meshes/MeshBuilder.h
  ZEngine/include/ZEngine/Rendering/Meshes/MeshLight.h
  ZEngine/include/ZEngine/Rendering/Renderers/Pipelines/GraphicRendererPipelineContext.h
  ZEngine/include/ZEngine/Rendering/Scenes/GraphicScene.h
  ZEngine/include/ZEngine/Rendering/Scenes/GraphicScene2D.h
  ZEngine/include/ZEngine/Rendering/Scenes/GraphicScene3D.h
  ZEngine/include/ZEngine/ZEngine.h
  ZEngine/include/ZEngine/ZEngineDef.h
  ZEngine/src/GraphicRendererDisassembleStage.cpp
  ZEngine/src/GraphicScene.cpp
  ZEngine/src/GraphicSceneEntity.cpp
  ZEngine/src/IDevice.cpp
  ZEngine/src/IPipelineStage.cpp
  ZEngine/src/Light.cpp
  ZEngine/src/MeshBuilder.cpp
  ZEngine/src/PerspectiveCameraController.cpp
  ZEngine/src/ShaderCompiler.cpp
  ZEngine/src/StandardMaterial.cpp
Labels: enhancement, Feature request, area-rendering, area-linux, area-window, area-ui, area-macOS

#183 renamed editor layers
  Tetragrama/src/Components/SceneViewportUIComponent.cpp
  Tetragrama/src/Editor.cpp
  Tetragrama/src/Editor.h
  Tetragrama/src/Layers/RenderLayer.cpp
  Tetragrama/src/Layers/RenderLayer.h
  Tetragrama/src/Layers/UILayer.cpp
  Tetragrama/src/Layers/UILayer.h
Labels: enhancement

#184 Component properties visualization in Inspector view
  Tetragrama/src/Components/HierarchyViewUIComponent.cpp
  Tetragrama/src/Components/HierarchyViewUIComponent.h
  Tetragrama/src/Components/InspectorViewUIComponent.cpp
  Tetragrama/src/Components/InspectorViewUIComponent.h
  Tetragrama/src/Editor.cpp
  Tetragrama/src/Layers/RenderLayer.cpp
  Tetragrama/src/Layers/UILayer.cpp
  Tetragrama/src/MessageToken.h
  Tetragrama/src/Messengers/Message.h
  ZEngine/include/ZEngine/Controllers/OrbitCameraController.h
  ZEngine/include/ZEngine/Controllers/PerspectiveCameraController.h
  ZEngine/include/ZEngine/Rendering/Cameras/Camera.h
  ZEngine/include/ZEngine/Rendering/Cameras/CameraEnum.h
  ZEngine/include/ZEngine/Rendering/Cameras/OrbitCamera.h
  ZEngine/include/ZEngine/Rendering/Cameras/PerspectiveCamera.h
  ZEngine/include/ZEngine/Rendering/Components/TransformComponent.h
  ZEngine/include/ZEngine/Rendering/Entities/GraphicSceneEntity.h
  ZEngine/include/ZEngine/Rendering/Geometries/GeometryEnum.h
  ZEngine/include/ZEngine/Rendering/Geometries/IGeometry.h
  ZEngine/include/ZEngine/Rendering/Scenes/GraphicScene.h
  ZEngine/src/CubeGeometry.cpp
  ZEngine/src/GlfwWindow/OpenGLWindow.cpp
  ZEngine/src/GraphicScene.cpp
  ZEngine/src/OrbitCameraController.cpp
  ZEngine/src/OrthographicCamera.cpp
  ZEngine/src/PerspectiveCamera.cpp
  ZEngine/src/PerspectiveCameraController.cpp
Labels: area-ui

#185 added default layout ini file
  Resources/Editor/Settings/DefaultLayout.ini
  Scripts/PostBuild.ps1
  ZEngine/src/ImguiLayer.cpp
Labels: enhancement, area-ui

#188 added entity material component visualization
  Tetragrama/src/Components/InspectorViewUIComponent.cpp
  Tetragrama/src/Helpers/UIComponentDrawerHelper.cpp
  Tetragrama/src/Helpers/UIComponentDrawerHelper.h
  ZEngine/include/ZEngine/Rendering/Materials/StandardMaterial.h
  ZEngine/include/ZEngine/Rendering/Textures/Texture.h
  ZEngine/src/StandardMaterial.cpp
Labels: Feature request

#189 polished editor UI
  Resources/Editor/Fonts/LICENSE.txt
  Resources/Editor/Fonts/OpenSans-Italic-VariableFont_wdth,wght.ttf
  Resources/Editor/Fonts/OpenSans-VariableFont_wdth,wght.ttf
  Resources/Editor/Fonts/OpenSans/OpenSans-Bold.ttf
  Resources/Editor/Fonts/OpenSans/OpenSans-BoldItalic.ttf
  Resources/Editor/Fonts/OpenSans/OpenSans-ExtraBold.ttf
  Resources/Editor/Fonts/OpenSans/OpenSans-ExtraBoldItalic.ttf
  Resources/Editor/Fonts/OpenSans/OpenSans-Italic.ttf
  Resources/Editor/Fonts/OpenSans/OpenSans-Light.ttf
  Resources/Editor/Fonts/OpenSans/OpenSans-LightItalic.ttf
  Resources/Editor/Fonts/OpenSans/OpenSans-Medium.ttf
  Resources/Editor/Fonts/OpenSans/OpenSans-MediumItalic.ttf
  Resources/Editor/Fonts/OpenSans/OpenSans-Regular.ttf
  Resources/Editor/Fonts/OpenSans/OpenSans-SemiBold.ttf
  Resources/Editor/Fonts/OpenSans/OpenSans-SemiBoldItalic.ttf
  Resources/Editor/Fonts/README.txt
  Scripts/PostBuild.ps1
  Tetragrama/src/Components/HierarchyViewUIComponent.cpp
  Tetragrama/src/Components/HierarchyViewUIComponent.h
  Tetragrama/src/Components/InspectorViewUIComponent.cpp
  Tetragrama/src/Components/InspectorViewUIComponent.h
  Tetragrama/src/Helpers/UIComponentDrawerHelper.cpp
  Tetragrama/src/Helpers/UIComponentDrawerHelper.h
  Tetragrama/src/Layers/UILayer.cpp
  Tetragrama/src/MessageToken.h
  ZEngine/include/ZEngine/Layers/ImguiLayer.h
  ZEngine/include/ZEngine/Rendering/Components/TransformComponent.h
  ZEngine/include/ZEngine/Rendering/Entities/GraphicSceneEntity.h
  ZEngine/include/ZEngine/Rendering/Materials/StandardMaterial.h
  ZEngine/include/ZEngine/Rendering/Scenes/GraphicScene.h
  ZEngine/src/GraphicScene.cpp
  ZEngine/src/ImguiLayer.cpp
  ZEngine/src/StandardMaterial.cpp
Labels: area-ui

#191 some fixes around windowing and UI components
  Resources/Editor/Settings/DefaultLayout.ini
  Tetragrama/src/Components/AboutUIComponent.h
  Tetragrama/src/Components/DemoUIComponent.h
  Tetragrama/src/Components/DockspaceUIComponent.cpp
  Tetragrama/src/Components/DockspaceUIComponent.h
  Tetragrama/src/Components/HierarchyViewUIComponent.cpp
  Tetragrama/src/Components/HierarchyViewUIComponent.h
  Tetragrama/src/Components/InspectorViewUIComponent.cpp
  Tetragrama/src/Components/InspectorViewUIComponent.h
  Tetragrama/src/Components/LogUIComponent.cpp
  Tetragrama/src/Components/LogUIComponent.h
  Tetragrama/src/Components/ProjectViewUIComponent.cpp
  Tetragrama/src/Components/ProjectViewUIComponent.h
  Tetragrama/src/Components/SceneViewportUIComponent.cpp
  Tetragrama/src/Components/SceneViewportUIComponent.h
  ZEngine/include/ZEngine/Components/UIComponent.h
  ZEngine/src/GlfwWindow/OpenGLWindow.cpp
  ZEngine/src/UIComponent.cpp
Labels: enhancement, area-ui

#193 Refactoring ZEngine build scripts
  .github/workflows/linux-build.yml
  .github/workflows/macOS-build.yml
  .github/workflows/window-build.yml
  CMakeLists.txt
  README.md
  Scripts/BuildEngine.ps1
  Scripts/PostBuild.ps1
Labels: enhancement, DevOps

#194 Improving Log UI output text colors
  Tetragrama/src/Components/LogUIComponent.cpp
  Tetragrama/src/Components/LogUIComponent.h
  Tetragrama/src/Helpers/UIComponentDrawerHelper.cpp
  Tetragrama/src/Helpers/UIComponentDrawerHelper.h
Labels: enhancement, area-ui

#196 adding editor camera
  Tetragrama/src/Components/HierarchyViewUIComponent.cpp
  Tetragrama/src/Components/HierarchyViewUIComponent.h
  Tetragrama/src/EditorCamera.cpp
  Tetragrama/src/EditorCamera.h
  Tetragrama/src/EditorCameraController.cpp
  Tetragrama/src/EditorCameraController.h
  Tetragrama/src/Layers/RenderLayer.cpp
  Tetragrama/src/Layers/RenderLayer.h
  Tetragrama/src/Layers/UILayer.cpp
  Tetragrama/src/MessageToken.h
  ZEngine/include/ZEngine/Inputs/KeyCodeDefinition.h
  ZEngine/include/ZEngine/Inputs/Mouse.h
  ZEngine/include/ZEngine/Rendering/Cameras/Camera.h
  ZEngine/include/ZEngine/Rendering/Scenes/GraphicScene.h
  ZEngine/src/GraphicScene.cpp
Labels: Feature request

#200 added support of multiple materials
  Resources/Unix/Shaders/mixed_texture_shader.glsl
  Resources/Windows/Shaders/mixed_texture_shader.glsl
  Tetragrama/src/Components/InspectorViewUIComponent.cpp
  ZEngine/include/ZEngine/Helpers/ContainerExtension.h
  ZEngine/include/ZEngine/Rendering/Components/MaterialComponent.h
  ZEngine/include/ZEngine/Rendering/Materials/BasicMaterial.h
  ZEngine/include/ZEngine/Rendering/Materials/IMaterial.h
  ZEngine/include/ZEngine/Rendering/Materials/MixedTextureMaterial.h
  ZEngine/include/ZEngine/Rendering/Materials/ShaderMaterial.h
  ZEngine/include/ZEngine/Rendering/Materials/StandardMaterial.h
  ZEngine/include/ZEngine/Rendering/Meshes/Mesh.h
  ZEngine/include/ZEngine/Rendering/Renderers/GraphicRendererInformation.h
  ZEngine/include/ZEngine/Rendering/Renderers/Storages/GraphicRendererStorage.h
  ZEngine/include/ZEngine/Rendering/Textures/Texture.h
  ZEngine/include/ZEngine/ZEngine.h
  ZEngine/include/ZEngine/pch.h
  ZEngine/src/BasicMaterial.cpp
  ZEngine/src/GraphicRenderer2D.cpp
  ZEngine/src/GraphicRendererDisassembleStage.cpp
  ZEngine/src/GraphicRendererDrawStage.cpp
  ZEngine/src/GraphicRendererStorageGenerationStage.cpp
  ZEngine/src/GraphicScene.cpp
  ZEngine/src/GraphicScene3DSerializer.cpp
  ZEngine/src/Mesh.cpp
  ZEngine/src/MeshBuilder.cpp
  ZEngine/src/MixedTextureMaterial.cpp
  ZEngine/src/ShaderMaterial.cpp
  ZEngine/src/StandardMaterial.cpp
Labels: Feature request, area-rendering

#201 Added support of Uniform buffer
  Resources/Unix/Shaders/basic_shader.glsl
  Resources/Unix/Shaders/standard_shader.glsl
  Resources/Windows/Shaders/basic_shader.glsl
  Resources/Windows/Shaders/standard_shader.glsl
  ZEngine/include/ZEngine/Rendering/Buffers/BufferLayout.h
  ZEngine/include/ZEngine/Rendering/Buffers/GraphicBuffer.h
  ZEngine/include/ZEngine/Rendering/Buffers/IndexBuffer.h
  ZEngine/include/ZEngine/Rendering/Buffers/UniformBuffer.h
  ZEngine/include/ZEngine/Rendering/Buffers/VertexBuffer.h
  ZEngine/include/ZEngine/Rendering/Materials/StandardMaterial.h
  ZEngine/include/ZEngine/Rendering/Renderers/Pipelines/GraphicRendererDrawStage.h
  ZEngine/src/GraphicRendererDrawStage.cpp
  ZEngine/src/StandardMaterial.cpp
Labels: Feature request, area-rendering
