Repository JeanPhilippeKernel/RendererEngine, pull requests merged in 2023-11, with the labels that each got.

#272 Revisiting Camera implementation
  Resources/Shaders/final_color.vert
  Tetragrama/src/Components/HierarchyViewUIComponent.cpp
  Tetragrama/src/Components/InspectorViewUIComponent.cpp
  Tetragrama/src/EditorCamera.cpp
  Tetragrama/src/EditorCamera.h
  Tetragrama/src/EditorCameraController.cpp
  Tetragrama/src/EditorCameraController.h
  Tetragrama/src/Layers/RenderLayer.cpp
  ZEngine/include/ZEngine/Controllers/CameraControllerTypeEnums.h
  ZEngine/include/ZEngine/Controllers/FirstPersonShooterCameraController.h
  ZEngine/include/ZEngine/Controllers/ICameraController.h
  ZEngine/include/ZEngine/Controllers/IController.h
  ZEngine/include/ZEngine/Controllers/OrbitCameraController.h
  ZEngine/include/ZEngine/Controllers/OrthographicCameraController.h
  ZEngine/include/ZEngine/Controllers/PerspectiveCameraController.h
  ZEngine/include/ZEngine/Rendering/Cameras/Camera.h
  ZEngine/include/ZEngine/Rendering/Cameras/FirstPersonShooterCamera.h
  ZEngine/include/ZEngine/Rendering/Cameras/OrbitCamera.h
  ZEngine/include/ZEngine/Rendering/Cameras/OrthographicCamera.h
  ZEngine/include/ZEngine/Rendering/Cameras/PerspectiveCamera.h
  ZEngine/include/ZEngine/Rendering/Renderers/Contracts/RendererDataContract.h
  ZEngine/include/ZEngine/ZEngine.h
  ZEngine/src/CameraController.cpp
  ZEngine/src/CommandBuffer.cpp
  ZEngine/src/FirstPersonShooterCamera.cpp
  ZEngine/src/FirstPersonShooterCameraController.cpp
  ZEngine/src/GraphicScene3DSerializer.cpp
  ZEngine/src/OrbitCamera.cpp
  ZEngine/src/OrbitCameraController.cpp
  ZEngine/src/OrthographicCamera.cpp
  ZEngine/src/OrthographicCameraController.cpp
  ZEngine/src/PerspectiveCamera.cpp
  ZEngine/src/PerspectiveCameraController.cpp
  ZEngine/src/RendererPipeline.cpp
  ZEngine/src/SceneRenderer.cpp
Labels: enhancement, Feature request, area-rendering

#273 Introducing Grid system
  Resources/Shaders/infinite_grid.frag
  Resources/Shaders/infinite_grid.vert
  ZEngine/include/ZEngine/Rendering/Buffers/Framebuffer.h
  ZEngine/include/ZEngine/Rendering/Pools/CommandPool.h
  ZEngine/include/ZEngine/Rendering/Renderers/GraphicRenderer.h
  ZEngine/include/ZEngine/Rendering/Renderers/ImGUIRenderer.h
  ZEngine/include/ZEngine/Rendering/Renderers/RenderPasses/RenderPass.h
  ZEngine/include/ZEngine/Rendering/Renderers/SceneRenderer.h
  ZEngine/include/ZEngine/Rendering/Specifications/FrameBufferSpecification.h
  ZEngine/include/ZEngine/Rendering/Specifications/GraphicRendererPipelineSpecification.h
  ZEngine/src/CommandBuffer.cpp
  ZEngine/src/CommandPool.cpp
  ZEngine/src/FrameBuffer.cpp
  ZEngine/src/GraphicRenderer.cpp
  ZEngine/src/ImGUIRenderer.cpp
  ZEngine/src/ImguiLayer.cpp
  ZEngine/src/RenderPass.cpp
  ZEngine/src/RendererPipeline.cpp
  ZEngine/src/SceneRenderer.cpp
  ZEngine/src/VulkanDevice.cpp
Labels: Feature request, area-rendering, vulkan-api

#282 Fixing shader errors validation
  Resources/Shaders/final_color.vert
  Resources/Shaders/infinite_grid.frag
  Resources/Shaders/infinite_grid.vert
  Resources/Shaders/utility.glsl
  Resources/Shaders/vertex_common.glsl
  Scripts/BuildEngine.ps1
  Scripts/ShaderCompile.ps1
  Scripts/Shared.ps1
  ZEngine/include/ZEngine/Rendering/Renderers/SceneRenderer.h
  ZEngine/src/VulkanDevice.cpp
  repoConfiguration.json
Labels: enhancement, Feature request, DevOps

#283 Added unit tests to the pipline
  .github/workflows/window-build.yml
  Scripts/RunTests.ps1
Labels: enhancement, DevOps

#284 IntrusivePtr follow-up
  ZEngine/include/ZEngine/Helpers/IntrusivePtr.h
  ZEngine/include/ZEngine/Helpers/IntrusiveWeakPtr.h
  ZEngine/tests/IntrusivePtr_test.cpp
  ZEngine/tests/IntrusiveWeakPtr_test.cpp
Labels: enhancement

#286 spread the use of IntrusivePtr
  Tetragrama/src/Editor.h
  Tetragrama/src/Layers/UILayer.cpp
  Tetragrama/src/Messengers/Messenger.h
  ZEngine/include/ZEngine/Components/UIComponent.h
  ZEngine/include/ZEngine/Controllers/IController.h
  ZEngine/include/ZEngine/Core/IPipeline.h
  ZEngine/include/ZEngine/Core/ISerializer.h
  ZEngine/include/ZEngine/Helpers/IntrusivePtr.h
  ZEngine/include/ZEngine/Inputs/IDevice.h
  ZEngine/include/ZEngine/Layers/ImguiLayer.h
  ZEngine/include/ZEngine/Layers/Layer.h
  ZEngine/include/ZEngine/Logging/Logger.h
  ZEngine/include/ZEngine/Rendering/Buffers/CommandBuffer.h
  ZEngine/include/ZEngine/Rendering/Buffers/Framebuffer.h
  ZEngine/include/ZEngine/Rendering/Buffers/GraphicBuffer.h
  ZEngine/include/ZEngine/Rendering/Buffers/Image2DBuffer.h
  ZEngine/include/ZEngine/Rendering/Buffers/StorageBuffer.h
  ZEngine/include/ZEngine/Rendering/Buffers/UniformBuffer.h
  ZEngine/include/ZEngine/Rendering/Cameras/Camera.h
  ZEngine/include/ZEngine/Rendering/Entities/GraphicSceneEntity.h
  ZEngine/include/ZEngine/Rendering/Geometries/IGeometry.h
  ZEngine/include/ZEngine/Rendering/Lights/Light.h
  ZEngine/include/ZEngine/Rendering/Materials/IMaterial.h
  ZEngine/include/ZEngine/Rendering/Meshes/MeshBuilder.h
  ZEngine/include/ZEngine/Rendering/Pools/CommandPool.h
  ZEngine/include/ZEngine/Rendering/Primitives/Fence.h
  ZEngine/include/ZEngine/Rendering/Primitives/Semaphore.h
  ZEngine/include/ZEngine/Rendering/Renderers/Pipelines/RendererPipeline.h
  ZEngine/include/ZEngine/Rendering/Renderers/RenderPasses/Attachment.h
  ZEngine/include/ZEngine/Rendering/Renderers/RenderPasses/RenderPass.h
  ZEngine/include/ZEngine/Rendering/Renderers/SceneRenderer.h
  ZEngine/include/ZEngine/Rendering/Scenes/GraphicScene.h
  ZEngine/include/ZEngine/Rendering/Shaders/Compilers/ShaderCompiler.h
  ZEngine/include/ZEngine/Rendering/Shaders/Shader.h
  ZEngine/include/ZEngine/Rendering/Swapchain.h
  ZEngine/include/ZEngine/Rendering/Textures/Texture.h
  ZEngine/include/ZEngine/Serializers/GraphicSceneSerializer.h
  ZEngine/include/ZEngine/Window/CoreWindow.h
  ZEngine/include/ZEngine/ZEngineDef.h
  ZEngine/src/CompilationStage.cpp
  ZEngine/src/FrameBuffer.cpp
  ZEngine/src/GlfwWindow/VulkanWindow.cpp
  ZEngine/src/GraphicRenderer.cpp
  ZEngine/src/GraphicScene.cpp
  ZEngine/src/GraphicSceneEntity.cpp
  ZEngine/src/ImguiLayer.cpp
  ZEngine/src/LinkageStage.cpp
  ZEngine/src/Logger.cpp
  ZEngine/src/MeshBuilder.cpp
  ZEngine/src/UIComponent.cpp
Labels: enhancement, critical
