Repository JeanPhilippeKernel/RendererEngine, pull requests merged in 2024-06, with the labels that each got.

#325 Render Scene from engine files
  Resources/Shaders/depth_prepass_scene.vert
  Resources/Shaders/final_color.vert
  Resources/Shaders/vertex_common.glsl
  Tetragrama/src/Components/DockspaceUIComponent.cpp
  Tetragrama/src/Components/HierarchyViewUIComponent.cpp
  Tetragrama/src/Components/HierarchyViewUIComponent.h
  Tetragrama/src/Importers/AssetImporter.cpp
  Tetragrama/src/Importers/IAssetImporter.h
  ZEngine/include/ZEngine/Rendering/Renderers/SceneRenderer.h
  ZEngine/include/ZEngine/Rendering/Scenes/GraphicScene.h
  ZEngine/src/GraphicScene.cpp
  ZEngine/src/SceneRenderer.cpp
Labels: area-rendering, area-ui

#330 Removing NuGet from User local path
  Scripts/Shared.ps1
Labels: enhancement, DevOps, scripting

#333 Revisting threadpool impl + Fix GTest failures
  ZEngine/include/ZEngine/Helpers/ThreadPool.h
  ZEngine/include/ZEngine/Helpers/ThreadSafeQueue.h
  ZEngine/src/ThreadPool.cpp
  ZEngine/tests/ThreadPool_test.cpp
Labels: DevOps

#336 add the python installation in the readme file
  README.md
Labels: enhancement, DevOps

#335 fix path error
  Scripts/BuildEngine.ps1
  Scripts/Shared.ps1
Labels: bug, DevOps, scripting

#337 Moving Panzerfaust from Console to UI Application
  Panzerfaust/App.axaml
  Panzerfaust/App.axaml.cs
  Panzerfaust/Assets/Icons.axaml
  Panzerfaust/Assets/avalonia-logo.ico
  Panzerfaust/Converters/BitmapAssetValueConverter.cs
  Panzerfaust/Converters/TypeConverters.cs
  Panzerfaust/Extensions/ServiceCollectionExtensions.cs
  Panzerfaust/Helpers/ImageHelper.cs
  Panzerfaust/Models/DefaultImportDir.cs
  Panzerfaust/Models/ListItemTemplate.cs
  Panzerfaust/Models/Project.cs
  Panzerfaust/Models/SceneList.cs
  Panzerfaust/Panzerfaust.csproj
  Panzerfaust/Program.cs
  Panzerfaust/Service/AppEnvironment/AppEnvironmentService.cs
  Panzerfaust/Service/AppEnvironment/IAppEnvironmentService.cs
  Panzerfaust/Service/Engine/EngineService.cs
  Panzerfaust/Service/Engine/IEngineService.cs
  Panzerfaust/Templates/ContentExample.axaml
  Panzerfaust/Templates/ContentExample.axaml.cs
  Panzerfaust/Validations/IValidationRule.cs
  Panzerfaust/Validations/IValidity.cs
  Panzerfaust/Validations/IsNotNullOrEmptyRule.cs
  Panzerfaust/Validations/ValidatableObject.cs
  Panzerfaust/ViewLocator.cs
  Panzerfaust/ViewModels/Base/ViewModelBase.cs
  Panzerfaust/ViewModels/CustomSplashScreenViewModel.cs
  Panzerfaust/ViewModels/HomePageViewModel.cs
  Panzerfaust/ViewModels/MainViewModel.cs
  Panzerfaust/ViewModels/SettingsViewModel.cs
  Panzerfaust/Views/CustomSplashScreenView.axaml
  Panzerfaust/Views/CustomSplashScreenView.axaml.cs
  Panzerfaust/Views/HomePageView.axaml
  Panzerfaust/Views/HomePageView.axaml.cs
  Panzerfaust/Views/MainView.axaml
  Panzerfaust/Views/MainView.axaml.cs
  Panzerfaust/Views/MainWindow.axaml
  Panzerfaust/Views/MainWindow.axaml.cs
  Panzerfaust/Views/SettingsView.axaml
  Panzerfaust/Views/SettingsView.axaml.cs
  Panzerfaust/app.manifest
Labels: Feature request, area-ui, Panzerfaust-Launcher
