Repository JeanPhilippeKernel/RendererEngine, pull requests merged in 2024-07, with the labels that each got.

#346 skipping test executables
  Scripts/BuildEngine.ps1
Labels: enhancement

#349 Fixing duplicate PackageReference
  Panzerfaust/Panzerfaust.csproj
Labels: enhancement, Panzerfaust-Launcher

#344 minor changes to the existing shadermanager Implementation
  ZEngine/include/ZEngine/Managers/ShaderManager.h
  ZEngine/include/ZEngine/Rendering/Specifications/ShaderSpecification.h
  ZEngine/src/RenderPass.cpp
  ZEngine/src/RendererPipeline.cpp
  ZEngine/src/ShaderManager.cpp
Labels: enhancement, area-controllers

#353 Fixing add new node ops
  ZEngine/include/ZEngine/Rendering/Scenes/GraphicScene.h
  ZEngine/src/GraphicScene.cpp
Labels: area-rendering

#357 panzerfaust runs on macos
  .github/workflows/macOS-build.yml
  CMakeLists.txt
  Panzerfaust/.gitignore
  Panzerfaust/App.axaml
  Panzerfaust/CMakeLists.txt
  Panzerfaust/Panzerfaust.csproj
  Panzerfaust/Service/Engine/EngineService.cs
  Panzerfaust/ViewModels/MainViewModel.cs
  Scripts/BuildEngine.ps1
  Scripts/PostBuild.ps1
  Scripts/Shared.ps1
  Tetragrama/src/Importers/AssimpImporter.cpp
  ZEngine/include/ZEngine/Rendering/Shaders/ShaderIncluder.h
  ZEngine/include/ZEngine/ZEngineDef.h
  ZEngine/src/GlfwWindow/VulkanWindow.cpp
  ZEngine/src/VulkanDevice.cpp
  __externals/externals.cmake
  __externals/imgui/CMakeLists.txt
  repoConfiguration.json
Labels: area-macOS, Panzerfaust-Launcher

#359 Backfill RenderPass::Verify() method
  ZEngine/include/ZEngine/Rendering/Shaders/Shader.h
  ZEngine/src/RenderPass.cpp
  ZEngine/src/Shader.cpp
Labels: enhancement, vulkan-api

#361 Adding new build option to compile Panzerfaust only
  CMakeLists.txt
  README.md
  Scripts/BuildEngine.ps1
  Scripts/PostBuild.ps1
Labels: enhancement, Panzerfaust-Launcher
