Repository JeanPhilippeKernel/RendererEngine, pull requests merged in 2024-02, with the labels that each got.

#309 Automate submodule Update
  .github/workflows/window-build.yml
  README.md
  Scripts/BuildEngine.ps1
Labels: enhancement

#307 Fixing Engine running on Integrated GPU device
  ZEngine/include/ZEngine/Hardwares/VulkanDevice.h
  ZEngine/include/ZEngine/Rendering/Specifications/ShaderSpecification.h
  ZEngine/src/Engine.cpp
  ZEngine/src/ImGUIRenderer.cpp
  ZEngine/src/Shader.cpp
  ZEngine/src/Swapchain.cpp
  ZEngine/src/VulkanDevice.cpp
Labels: area-window, vulkan-api, critical

#306 Introducing Render Graph
  Resources/Shaders/cubemap.vert
  Resources/Shaders/depth_prepass_scene.vert
  Resources/Shaders/final_color.frag
  Resources/Shaders/fragment_common.glsl
  Resources/Shaders/g_buffer.frag
  Resources/Shaders/g_buffer.vert
  Resources/Shaders/infinite_grid.frag
  Resources/Shaders/infinite_grid.vert
  Resources/Shaders/skybox.frag
  Resources/Shaders/skybox.vert
  Resources/Shaders/vertex_common.glsl
  ZEngine/include/ZEngine/Rendering/Buffers/CommandBuffer.h
  ZEngine/include/ZEngine/Rendering/Buffers/Framebuffer.h
  ZEngine/include/ZEngine/Rendering/Buffers/GraphicBuffer.h
  ZEngine/include/ZEngine/Rendering/Buffers/IndexBuffer.h
  ZEngine/include/ZEngine/Rendering/Buffers/IndirectBuffer.h
  ZEngine/include/ZEngine/Rendering/Buffers/StorageBuffer.h
  ZEngine/include/ZEngine/Rendering/Buffers/VertexBuffer.h
  ZEngine/include/ZEngine/Rendering/Renderers/Contracts/RendererDataContract.h
  ZEngine/include/ZEngine/Rendering/Renderers/GraphicRenderer.h
  ZEngine/include/ZEngine/Rendering/Renderers/ImGUIRenderer.h
  ZEngine/include/ZEngine/Rendering/Renderers/Pipelines/RendererPipeline.h
  ZEngine/include/ZEngine/Rendering/Renderers/RenderGraph.h
  ZEngine/include/ZEngine/Rendering/Renderers/RenderPasses/Attachment.h
  ZEngine/include/ZEngine/Rendering/Renderers/RenderPasses/RenderPass.h
  ZEngine/include/ZEngine/Rendering/Renderers/SceneRenderer.h
  ZEngine/include/ZEngine/Rendering/Scenes/GraphicScene.h
  ZEngine/include/ZEngine/Rendering/Specifications/FormatSpecification.h
  ZEngine/include/ZEngine/Rendering/Specifications/FrameBufferAttachmentSpecification.h
  ZEngine/include/ZEngine/Rendering/Specifications/FrameBufferSpecification.h
  ZEngine/include/ZEngine/Rendering/Specifications/GraphicRendererPipelineSpecification.h
  ZEngine/include/ZEngine/Rendering/Specifications/RenderPassSpecification.h
  ZEngine/include/ZEngine/Rendering/Specifications/TextureSpecification.h
  ZEngine/include/ZEngine/Rendering/Swapchain.h
  ZEngine/include/ZEngine/Rendering/Textures/Texture.h
  ZEngine/include/ZEngine/Rendering/Textures/Texture2D.h
  ZEngine/src/Attachment.cpp
  ZEngine/src/CommandBuffer.cpp
  ZEngine/src/Engine.cpp
  ZEngine/src/FrameBuffer.cpp
  ZEngine/src/GlfwWindow/VulkanWindow.cpp
  ZEngine/src/GraphicRenderer.cpp
  ZEngine/src/GraphicScene.cpp
  ZEngine/src/ImGUIRenderer.cpp
  ZEngine/src/RenderGraph.cpp
  ZEngine/src/RenderPass.cpp
  ZEngine/src/RendererPipeline.cpp
  ZEngine/src/SceneRenderer.cpp
  ZEngine/src/Shader.cpp
  ZEngine/src/Swapchain.cpp
  ZEngine/src/Texture2D.cpp
  ZEngine/src/VulkanDevice.cpp
Labels: Feature request
