Repository JeanPhilippeKernel/RendererEngine, pull requests merged in 2025-05, with the labels that each got.

#449 Revisiting import asset process
  Tetragrama/CMakeLists.txt
  Tetragrama/Components/DockspaceUIComponent.cpp
  Tetragrama/Components/DockspaceUIComponent.h
  Tetragrama/Components/HierarchyViewUIComponent.cpp
  Tetragrama/Components/HierarchyViewUIComponent.h
  Tetragrama/Editor.cpp
  Tetragrama/Editor.h
  Tetragrama/EditorScene.cpp
  Tetragrama/EditorScene.h
  Tetragrama/EntryPoint.cpp
  Tetragrama/Helpers/NodeHierarchyHelper.h
  Tetragrama/Helpers/SerializerCommonHelper.cpp
  Tetragrama/Helpers/SerializerCommonHelper.h
  Tetragrama/Importers/AssetTypes.h
  Tetragrama/Importers/AssimpImporter.cpp
  Tetragrama/Importers/AssimpImporter.h
  Tetragrama/Importers/IAssetImporter.cpp
  Tetragrama/Importers/IAssetImporter.h
  Tetragrama/Layers/ImguiLayer.cpp
  Tetragrama/Layers/ImguiLayer.h
  Tetragrama/Managers/AssetManager.cpp
  Tetragrama/Managers/AssetManager.h
  Tetragrama/Serializers/EditorSceneSerializer.cpp
  Tetragrama/Serializers/EditorSceneSerializer.h
  Tetragrama/Serializers/Serializer.h
  ZEngine/ZEngine/Core/Containers/HashMap.h
  ZEngine/ZEngine/Core/Containers/Strings.h
  ZEngine/ZEngine/Core/Memory/Allocator.cpp
  ZEngine/ZEngine/Core/Memory/Allocator.h
  ZEngine/ZEngine/Core/Memory/MemoryManager.h
  ZEngine/ZEngine/Engine.cpp
  ZEngine/ZEngine/Managers/IAssetManager.h
  ZEngine/ZEngine/Managers/IManager.h
  ZEngine/ZEngine/ZEngineDef.h
Labels: enhancement, Feature request

#451 Supporting open scene file by drag and drop operation
  Tetragrama/Components/DockspaceUIComponent.cpp
  Tetragrama/Components/DockspaceUIComponent.h
  Tetragrama/Components/LogUIComponent.cpp
  Tetragrama/Components/ProjectViewUIComponent.cpp
  Tetragrama/Components/SceneViewportUIComponent.cpp
  Tetragrama/EntryPoint.cpp
  Tetragrama/Importers/AssimpImporter.cpp
  Tetragrama/Importers/AssimpImporter.h
  Tetragrama/Importers/IAssetImporter.cpp
  Tetragrama/Importers/IAssetImporter.h
  Tetragrama/Layers/ImguiLayer.cpp
  Tetragrama/Managers/AssetManager.cpp
  Tetragrama/MessageToken.h
  Tetragrama/Serializers/Serializer.h
  ZEngine/ZEngine/Logging/Logger.h
Labels: enhancement, Feature request, area-window, area-macOS

#448 Matrix Library
  ZEngine/ZEngine/CMakeLists.txt
  ZEngine/ZEngine/Core/Maths/Matrix.h
  ZEngine/ZEngine/Core/Maths/Vec.h
  ZEngine/ZEngine/Core/Maths/typedefs.h
  ZEngine/tests/Maths/Matrix_test.cpp
  ZEngine/tests/Maths/Vector_test.cpp
Labels: Feature request, area-window, area-macOS

#452 Mapping Asset node hierarchy and Scene node hierarchy
  Tetragrama/Components/DockspaceUIComponent.cpp
  Tetragrama/Components/DockspaceUIComponent.h
  Tetragrama/Components/HierarchyViewUIComponent.cpp
  Tetragrama/Components/SceneViewportUIComponent.cpp
  Tetragrama/Editor.cpp
  Tetragrama/Editor.h
  Tetragrama/EditorScene.cpp
  Tetragrama/EditorScene.h
  Tetragrama/Importers/AssetTypes.h
  Tetragrama/Importers/IAssetImporter.cpp
  Tetragrama/Importers/IAssetImporter.h
  Tetragrama/Layers/ImguiLayer.cpp
  Tetragrama/Managers/AssetManager.cpp
  Tetragrama/Managers/AssetManager.h
  Tetragrama/MessageToken.h
  Tetragrama/Serializers/Serializer.h
  ZEngine/ZEngine/ZEngineDef.h
Labels: enhancement, Feature request, area-window, area-macOS
